# Generated by Django 5.2.3 on 2025-07-26 20:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GiyimUrunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori', models.CharField(blank=True, choices=[('Üst', 'Üst'), ('Alt', 'Alt'), ('Ayakkabı', 'Ayakkabı')], max_length=50)),
                ('mevcut_adet', models.PositiveIntegerField(default=0, verbose_name='Mevcut Stok')),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Giyim Ürünü',
                'verbose_name_plural': 'Giyim Ürünleri',
            },
        ),
        migrations.CreateModel(
            name='IslemTuru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='İşlem Türü Adı')),
                ('durum_degistirir_mi', models.BooleanField(default=False, verbose_name='Durum Değiştirir Mi?')),
                ('yeni_durum', models.CharField(blank=True, choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif')], max_length=10, null=True, verbose_name='Yeni Durum (Eğer Değiştirirse)')),
                ('yatak_guncelleme_gerektirir_mi', models.BooleanField(default=False, verbose_name='Yatak Güncelleme Gerektirir Mi?')),
            ],
            options={
                'verbose_name': 'İşlem Türü',
                'verbose_name_plural': 'İşlem Türleri',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_adi', models.CharField(max_length=255, verbose_name='Kurum Adı')),
            ],
        ),
        migrations.CreateModel(
            name='Misafir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosya_no', models.CharField(help_text='Kişiye özel benzersiz dosya numarası', max_length=30, unique=True, verbose_name='Dosya No')),
                ('ad', models.CharField(max_length=100, verbose_name='Adı')),
                ('soyad', models.CharField(max_length=100, verbose_name='Soyadı')),
                ('tc_kimlik_no', models.CharField(help_text='11 haneli T.C. Kimlik Numarası', max_length=11, unique=True, verbose_name='T.C. Kimlik No')),
                ('giris_tarihi', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Giriş Tarihi')),
                ('cikis_tarihi', models.DateTimeField(blank=True, null=True, verbose_name='Çıkış Tarihi')),
                ('cikis_nedeni', models.TextField(blank=True, help_text='Kişinin en son çıkış yapma nedeni.', null=True, verbose_name='Son Çıkış Nedeni')),
                ('dogum_tarihi', models.DateField(verbose_name='Doğum Tarihi')),
                ('dogum_yeri', models.CharField(max_length=100, verbose_name='Doğum Yeri')),
                ('telefon', models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefonu')),
                ('durum', models.CharField(choices=[('AKTIF', 'Aktif'), ('PASIF', 'Pasif')], default='AKTIF', max_length=10, verbose_name='Durum Bilgisi')),
                ('adres', models.TextField(blank=True, null=True, verbose_name='Adresi')),
                ('fotograf', models.ImageField(blank=True, null=True, upload_to='misafir_fotograflari/', verbose_name='Kişi Fotoğrafı')),
                ('beyan', models.TextField(blank=True, help_text='Kişinin kendi beyanı veya önemli notlar', null=True, verbose_name='Kişinin Beyanı')),
            ],
            options={
                'verbose_name': 'Misafir',
                'verbose_name_plural': 'Misafirler',
                'ordering': ['-giris_tarihi'],
            },
        ),
        migrations.CreateModel(
            name='SosyalGuvence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, unique=True, verbose_name='Sosyal Güvence Adı')),
            ],
            options={
                'verbose_name': 'Sosyal Güvence',
                'verbose_name_plural': 'Sosyal Güvenceler',
                'ordering': ['ad'],
            },
        ),
        migrations.CreateModel(
            name='UrunAdi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100, unique=True, verbose_name='Ürün Adı')),
            ],
            options={
                'verbose_name': 'Ürün Adı Tanımı',
                'verbose_name_plural': 'Ürün Adı Tanımları',
                'ordering': ['isim'],
            },
        ),
        migrations.CreateModel(
            name='Yatak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yatak_numarasi', models.CharField(max_length=10, unique=True, verbose_name='Yatak Numarası')),
                ('dolu_mu', models.BooleanField(default=False, verbose_name='Dolu Mu?')),
            ],
            options={
                'verbose_name': 'Yatak',
                'verbose_name_plural': 'Yataklar',
                'ordering': ['yatak_numarasi'],
            },
        ),
        migrations.CreateModel(
            name='YoklamaDurumu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Islem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('islem_no', models.CharField(help_text='Otomatik oluşturulan benzersiz işlem numarası', max_length=35, unique=True, verbose_name='İşlem Numarası')),
                ('islem_zamani', models.DateTimeField(auto_now_add=True, verbose_name='İşlem Zamanı')),
                ('aciklama', models.TextField(blank=True, help_text='Yapılan işlemle ilgili detaylı açıklama', null=True, verbose_name='İşlem Açıklaması')),
                ('tutar', models.DecimalField(decimal_places=2, default=0.0, help_text='Yapılan işlemin tutarı', max_digits=10, verbose_name='Tutar')),
                ('islem_turu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='kayitlar.islemturu', verbose_name='İşlem Türü')),
                ('kurum', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islemler', to='kayitlar.kurum')),
                ('misafir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='islemler', to='kayitlar.misafir', verbose_name='İlgili Misafir')),
            ],
            options={
                'verbose_name': 'İşlem',
                'verbose_name_plural': 'İşlemler',
                'ordering': ['-islem_zamani'],
            },
        ),
        migrations.CreateModel(
            name='GiyimIslem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(default=1)),
                ('islem_turu', models.CharField(choices=[('Giriş', 'Giriş'), ('Çıkış', 'Çıkış')], max_length=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.giyimurunu')),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.misafir')),
            ],
        ),
        migrations.AddField(
            model_name='misafir',
            name='sosyal_guvence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.sosyalguvence', verbose_name='Sosyal Güvencesi'),
        ),
        migrations.AddField(
            model_name='giyimurunu',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.urunadi', verbose_name='Ürün Adı'),
        ),
        migrations.AddField(
            model_name='misafir',
            name='yatak_no',
            field=models.ForeignKey(blank=True, help_text='Kişinin kaldığı yatak numarası', null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.yatak', verbose_name='Yatak Numarası'),
        ),
        migrations.CreateModel(
            name='YoklamaKaydi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(default=django.utils.timezone.now)),
                ('durum', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.yoklamadurumu')),
                ('kisi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.misafir')),
            ],
        ),
    ]
