# Generated by Django 5.2.4 on 2025-07-20 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kurum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kurum_adi', models.CharField(max_length=255, verbose_name='Kurum Adı')),
            ],
        ),
        migrations.AddField(
            model_name='islem',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='islemler', to='kayitlar.kurum'),
        ),
    ]
