# Generated by Django 5.2.3 on 2025-07-27 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giyimislem',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='alici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.misafir', verbose_name='Alıcı/Verici'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='islem_turu',
            field=models.CharField(choices=[('Giriş', 'Giriş'), ('Çıkış', 'Çıkış')], max_length=10, verbose_name='İşlem Türü'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='miktar',
            field=models.PositiveIntegerField(default=1, verbose_name='Miktar'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='tarih',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Tarih'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='urun',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.giyimurunu', verbose_name='Ürün'),
        ),
        migrations.AlterField(
            model_name='giyimurunu',
            name='aciklama',
            field=models.TextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='giyimurunu',
            name='kategori',
            field=models.CharField(blank=True, choices=[('Üst', 'Üst'), ('Alt', 'Alt'), ('Ayakkabı', 'Ayakkabı')], max_length=50, verbose_name='Kategori'),
        ),
        migrations.AlterUniqueTogether(
            name='giyimurunu',
            unique_together={('ad', 'kategori')},
        ),
    ]
