# Generated by Django 5.2.4 on 2025-07-21 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0002_kurum_islem_kurum'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiyimUrunu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=100, verbose_name='Ürün Adı')),
                ('kategori', models.CharField(blank=True, choices=[('Üst', 'Üst'), ('Alt', 'Alt'), ('Ayakkabı', 'Ayakkabı')], max_length=50)),
                ('mevcut_adet', models.PositiveIntegerField(default=0, verbose_name='Mevcut Stok')),
                ('aciklama', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiyimIslem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miktar', models.PositiveIntegerField(default=1)),
                ('islem_turu', models.CharField(choices=[('Giriş', 'Giriş'), ('Çıkış', 'Çıkış')], max_length=10)),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('aciklama', models.TextField(blank=True, null=True)),
                ('alici', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.misafir')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kayitlar.giyimurunu')),
            ],
        ),
    ]
