# Generated by Django 5.2.3 on 2025-07-27 08:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0002_alter_giyimislem_aciklama_alter_giyimislem_alici_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='giyimislem',
            options={'ordering': ['-tarih'], 'verbose_name': 'Stok Hareketi', 'verbose_name_plural': 'Stok Hareketleri'},
        ),
        migrations.AddField(
            model_name='giyimislem',
            name='kaynak_firma',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Giriş Kaynağı/Tedarikçi'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='alici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.misafir', verbose_name='Alıcı'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='miktar',
            field=models.PositiveIntegerField(verbose_name='Miktar'),
        ),
    ]
