# Generated by Django 5.2.3 on 2025-07-27 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0003_alter_giyimislem_options_giyimislem_kaynak_firma_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='islem',
            name='miktar',
            field=models.PositiveIntegerField(blank=True, help_text="Eğer işlem türü 'Ayni Yardım' ise verilen ürünün miktarı", null=True, verbose_name='Verilen Ayni Miktar'),
        ),
        migrations.AddField(
            model_name='islem',
            name='urun',
            field=models.ForeignKey(blank=True, help_text="Eğer işlem türü 'Ayni Yardım' ise verilen ürün", null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.giyimurunu', verbose_name='Verilen Ayni Ürün'),
        ),
    ]
