# Generated by Django 5.2.3 on 2025-07-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kayitlar', '0004_islem_miktar_islem_urun'),
    ]

    operations = [
        migrations.AddField(
            model_name='giyimislem',
            name='kurum',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.kurum', verbose_name='Alıcı (Kurum)'),
        ),
        migrations.AlterField(
            model_name='giyimislem',
            name='alici',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kayitlar.misafir', verbose_name='Alıcı (Misafir)'),
        ),
    ]
